export const ARDUPACKAGES_UPDATE_REQUEST = 'ARDUPACKAGES_UPDATE_REQUEST';
export const ARDUPACKAGES_UPDATE_POPUP_CLOSE =
  'ARDUPACKAGES_UPDATE_POPUP_CLOSE';
export const ARDUPACKAGES_UPGRADE_PROCEED = 'ARDUPACKAGES_UPGRADE_PROCEED';
