export const PATCH_CREATE_REQUESTED = 'PATCH_CREATE_REQUESTED';
export const PATCH_OR_FOLDER_RENAME_REQUESTED = 'PATCH_OR_FOLDER_RENAME_REQUESTED';
export const PATCH_OR_FOLDER_DELETE_REQUESTED = 'PATCH_OR_FOLDER_DELETE_REQUESTED';

export const POPUP_CANCEL = 'POPUP_CANCEL';

export const SET_SELECTION = 'SET_SELECTION';
