export const PATCH_CREATE_REQUESTED = 'PATCH_CREATE_REQUESTED';
export const PATCH_RENAME_REQUESTED = 'PATCH_RENAME_REQUESTED';
export const PATCH_DELETE_REQUESTED = 'PATCH_DELETE_REQUESTED';

export const PROJECT_RENAME_REQUESTED = 'PROJECT_RENAME_REQUESTED';

export const POPUP_CANCEL = 'POPUP_CANCEL';

export const SET_SELECTION = 'SET_SELECTION';
export const REMOVE_SELECTION = 'REMOVE_SELECTION';
