export const INVALID_WORKSPACE_PATH = 'INVALID_WORKSPACE_PATH';
export const WORKSPACE_DIR_NOT_EMPTY = 'WORKSPACE_DIR_NOT_EMPTY'; // & without xod-workspace
export const WORKSPACE_DIR_NOT_EXIST_OR_EMPTY = 'WORKSPACE_DIR_NOT_EXIST_OR_EMPTY';
export const CANT_CREATE_WORKSPACE_FILE = 'CANT_CREATE_WORKSPACE_FILE';
export const CANT_COPY_STDLIB = 'CANT_COPY_STDLIB';
export const CANT_COPY_DEFAULT_PROJECT = 'CANT_COPY_DEFAULT_PROJECT';
export const CANT_ENUMERATE_PROJECTS = 'CANT_ENUMERATE_PROJECTS';
export const CANT_SAVE_PROJECT = 'CANT_SAVE_PROJECT';
