dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libudev-dev
    - rpm

osx_image: xcode8.3

language: node_js
node_js: 6.0.0

matrix:
  include:
  - os: osx

git:
  depth: 5
cache:
  directories:
  - $HOME/.cache
  - $HOME/.electron
  - $HOME/.nvm
  - node_modules

script: ./tools/travis.sh
