language: node_js
node_js: '7'

matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
  - os: osx
    osx_image: xcode8.3

addons:
  apt:
    packages:
    - libudev-dev
    - rpm

git:
  depth: 5

cache:
  directories:
  - $HOME/.electron
  - node_modules
  yarn: true

install:
- yarn install

before_script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3; # give xvfb some time to start
  fi

script: ./tools/travis.sh
