export const UPLOAD = 'UPLOAD';

export const TOGGLE_DEBUGGER_PANEL = 'TOGGLE_DEBUGGER_PANEL';

export const DEBUGGER_LOG_ADD_MESSAGES = 'DEBUGGER_LOG_ADD_MESSAGES';
export const DEBUGGER_LOG_CLEAR = 'DEBUGGER_LOG_CLEAR';

export const DEBUG_SESSION_STARTED = 'DEBUG_SESSION_STARTED';
export const DEBUG_SESSION_STOPPED = 'DEBUG_SESSION_STOPPED';

export const DEBUG_DRILL_DOWN = 'DEBUG_DRILL_DOWN';

export const MARK_DEBUG_SESSION_OUTDATED = 'MARK_DEBUG_SESSION_OUTDATED';
