export const SHOW_DEBUGGER_PANEL = 'SHOW_DEBUGGER_PANEL';
export const HIDE_DEBUGGER_PANEL = 'HIDE_DEBUGGER_PANEL';
export const TOGGLE_DEBUGGER_PANEL = 'TOGGLE_DEBUGGER_PANEL';

export const DEBUGGER_LOG_ADD_MESSAGE = 'DEBUGGER_LOG_ADD_MESSAGE';
export const DEBUGGER_LOG_CLEAR = 'DEBUGGER_LOG_CLEAR';

export const DEBUG_SESSION_STARTED = 'DEBUG_SESSION_STARTED';
export const DEBUG_SESSION_STOPPED = 'DEBUG_SESSION_STOPPED';
