export const UPLOAD = 'UPLOAD';
export const INSTALL_ARDUINO_DEPENDENCIES = 'INSTALL_ARDUINO_DEPENDENCIES';
export const CHECK_ARDUINO_DEPENDENCIES = 'CHECK_ARDUINO_DEPENDENCIES';
export const UPGRADE_ARDUINO_DEPENDECIES = 'UPGRADE_ARDUINO_DEPENDECIES';

export const TOGGLE_DEBUGGER_PANEL = 'TOGGLE_DEBUGGER_PANEL';

export const SELECT_DEBUGGER_TAB = 'SELECT_DEBUGGER_TAB';

export const DEBUGGER_LOG_ADD_MESSAGES = 'DEBUGGER_LOG_ADD_MESSAGES';
export const DEBUGGER_LOG_CLEAR = 'DEBUGGER_LOG_CLEAR';
export const DEBUGGER_LOG_START_SKIPPING_NEW_LINES =
  'DEBUGGER_LOG_START_SKIPPING_NEW_LINES';
export const DEBUGGER_LOG_STOP_SKIPPING_NEW_LINES =
  'DEBUGGER_LOG_STOP_SKIPPING_NEW_LINES';
export const DEBUGGER_LOG_TOGGLE_XOD_PROTOCOL_MESSAGES =
  'DEBUGGER_LOG_TOGGLE_XOD_PROTOCOL_MESSAGES';

export const DEBUG_SESSION_STARTED = 'DEBUG_SESSION_STARTED';
export const SERIAL_SESSION_STARTED = 'SERIAL_SESSION_STARTED';
export const DEBUG_SESSION_STOPPED = 'DEBUG_SESSION_STOPPED';

export const DEBUG_DRILL_DOWN = 'DEBUG_DRILL_DOWN';

export const MARK_DEBUG_SESSION_OUTDATED = 'MARK_DEBUG_SESSION_OUTDATED';
