FROM node:9.2

# Dependencies for Electron, Spectron, electron-builder
RUN apt-get update && apt-get install -y \
  libasound2 \
  libgconf-2-4 \
  libgtk2.0-0 \
  libnss3 \
  libx11-xcb-dev \
  libxss1 \
  libxtst6 \
  rpm \
  xvfb
