export const NODE_MOVE = 'NODE_MOVE';
export const NODE_ADD = 'NODE_ADD';
export const NODE_DELETE = 'NODE_DELETE';

export const LINK_ADD = 'LINK_CREATE';
export const LINK_DELETE = 'LINK_DELETE';

export const META_UPDATE = 'META_UPDATE';
export const VIEWSTATE_UPDATE = 'VIEWSTATE_UPDATE';

export const PIN_CLICK = 'PIN_CLICK';

export const EDITOR_DESELECT_ALL = 'EDITOR_DESELECT_ALL';
export const EDITOR_SELECT_NODE = 'EDITOR_SELECT_NODE';
export const EDITOR_SELECT_PIN = 'EDITOR_SELECT_PIN';
export const EDITOR_SELECT_LINK = 'EDITOR_SELECT_LINK';
