export const REQUEST_SELECT_PROJECT = 'EVENT_REQUEST_SELECT_PROJECT';
export const REQUEST_SHOW_PROJECT = 'EVENT_REQUEST_SHOW_PROJECT';
export const REQUEST_CREATE_WORKSPACE = 'EVENT_REQUEST_CREATE_WORKSPACE';

export const CREATE_PROJECT = 'EVENT_CREATE_PROJECT';
export const OPEN_PROJECT = 'EVENT_OPEN_PROJECT';
export const SELECT_PROJECT = 'EVENT_SELECT_PROJECT';
export const SAVE_PROJECT = 'EVENT_SAVE_PROJECT';

export const LIST_BOARDS = 'EVENT_LIST_BOARDS';
export const LIST_PORTS = 'EVENT_LIST_PORTS';
export const GET_SELECTED_BOARD = 'EVENT_GET_SELECTED_BOARD';
export const SET_SELECTED_BOARD = 'EVENT_SET_SELECTED_BOARD';

export const SWITCH_WORKSPACE = 'EVENT_SWITCH_WORKSPACE';
export const CREATE_WORKSPACE = 'EVENT_CREATE_WORKSPACE';
export const UPDATE_WORKSPACE = 'UPDATE_WORKSPACE';

export const WORKSPACE_ERROR = 'EVENT_WORKSPACE_ERROR';
