export const EDITOR_DESELECT_ALL = 'EDITOR_DESELECT_ALL';
export const EDITOR_SELECT_PIN = 'EDITOR_SELECT_PIN';
export const EDITOR_DESELECT_PIN = 'EDITOR_DESELECT_PIN';
export const EDITOR_SELECT_ENTITY = 'EDITOR_SELECT_ENTITY';
export const EDITOR_DESELECT_ENTITY = 'EDITOR_DESELECT_ENTITY';
export const EDITOR_ADD_ENTITY_TO_SELECTION = 'EDITOR_ADD_ENTITY_TO_SELECTION';
export const EDITOR_SET_MODE = 'EDITOR_SET_MODE';
export const EDITOR_SET_SELECTED_NODETYPE = 'EDITOR_SET_SELECTED_NODETYPE';
export const EDITOR_SWITCH_PATCH = 'EDITOR_SWITCH_PATCH';

export const SET_CURRENT_PATCH_OFFSET = 'SET_CURRENT_PATCH_OFFSET';

export const SET_FOCUSED_AREA = 'SET_FOCUSED_AREA';

export const PASTE_ENTITIES = 'PASTE_ENTITIES';

export const TAB_CLOSE = 'TAB_CLOSE';
export const TAB_SORT = 'TAB_SORT';

export const TOGGLE_HELPBAR = 'TOGGLE_HELPBAR';

export const SHOW_SUGGESTER = 'SHOW_SUGGESTER';
export const HIDE_SUGGESTER = 'HIDE_SUGGESTER';
export const HIGHLIGHT_SUGGESTER_ITEM = 'HIGHLIGHT_SUGGESTER_ITEM';

export const START_DRAGGING_PATCH = 'START_DRAGGING_PATCH';
