export const UPLOAD = 'UPLOAD';
export const UPLOAD_TO_ARDUINO = 'UPLOAD_TO_ARDUINO';
export const OPEN_UPLOAD_CONFIG = 'OPEN_UPLOAD_CONFIG';
export const CLOSE_UPLOAD_CONFIG = 'CLOSE_UPLOAD_CONFIG';
export const OPEN_CONNECT_SERIAL_DIALOG = 'OPEN_CONNECT_SERIAL_DIALOG';
export const CLOSE_CONNECT_SERIAL_DIALOG = 'CLOSE_CONNECT_SERIAL_DIALOG';
export const SELECT_SERIAL_PORT = 'SELECT_SERIAL_PORT';

export default {
  UPLOAD,
  UPLOAD_TO_ARDUINO,
  OPEN_UPLOAD_CONFIG,
  CLOSE_UPLOAD_CONFIG,
  OPEN_CONNECT_SERIAL_DIALOG,
  CLOSE_CONNECT_SERIAL_DIALOG,
  SELECT_SERIAL_PORT,
};
