export const UPLOAD = 'UPLOAD';
export const UPLOAD_TO_ARDUINO = 'UPLOAD_TO_ARDUINO';
export const OPEN_UPLOAD_CONFIG = 'OPEN_UPLOAD_CONFIG';
export const CLOSE_UPLOAD_CONFIG = 'CLOSE_UPLOAD_CONFIG';
export const SELECT_SERIAL_PORT = 'SELECT_SERIAL_PORT';
export const REQUEST_INSTALL_ARDUINO_IDE = 'REQUEST_INSTALL_ARDUINO_IDE';

export default {
  UPLOAD,
  UPLOAD_TO_ARDUINO,
  OPEN_UPLOAD_CONFIG,
  CLOSE_UPLOAD_CONFIG,
  REQUEST_INSTALL_ARDUINO_IDE,
  SELECT_SERIAL_PORT,
};
