export const CREATE_WORKSPACE_REQUESTED = 'CREATE_WORKSPACE_REQUESTED';
export const SWITCH_WORKSPACE_REQUESTED = 'SWITCH_WORKSPACE_REQUESTED';

export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const SWITCH_WORKSPACE = 'SWITCH_WORKSPACE';
