export const SET_WORKSPACE = 'SET_WORKSPACE';
export const CHECK_WORKSPACE = 'CHECK_WORKSPACE';
export const REQUEST_WORKSPACE = 'REQUEST_WORKSPACE';
export const CHANGE_WORKSPACE = 'CHANGE_WORKSPACE';

export default {
  SET_WORKSPACE,
  CHECK_WORKSPACE,
  REQUEST_WORKSPACE,
  CHANGE_WORKSPACE,
};
