export const PROJECT_CREATE_REQUESTED = 'PROJECT_CREATE_REQUESTED';
export const PROJECT_OPEN_REQUESTED = 'PROJECT_OPEN_REQUESTED';

export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_RENAME = 'PROJECT_RENAME';
export const PROJECT_OPEN = 'PROJECT_OPEN';
export const PROJECT_IMPORT = 'PROJECT_IMPORT';
export const PROJECT_OPEN_WORKSPACE = 'PROJECT_OPEN_WORKSPACE';
export const PROJECT_UPDATE_META = 'PROJECT_UPDATE_META';

export const NODE_MOVE = 'NODE_MOVE';
export const NODE_ADD = 'NODE_ADD';
export const NODE_DELETE = 'NODE_DELETE';
export const NODE_UPDATE_PROPERTY = 'NODE_UPDATE_PROPERTY';

export const LINK_ADD = 'LINK_ADD';
export const LINK_DELETE = 'LINK_DELETE';

export const PATCH_ADD = 'PATCH_ADD';
export const PATCH_RENAME = 'PATCH_RENAME';
export const PATCH_DELETE = 'PATCH_DELETE';
export const PATCH_DESCRIPTION_UPDATE = 'PATCH_DESCRIPTION_UPDATE';

export const PATCH_HISTORY_UNDO = 'PATCH_HISTORY_UNDO';
export const PATCH_HISTORY_REDO = 'PATCH_HISTORY_REDO';
