export const PROJECT_CREATE_REQUESTED = 'PROJECT_CREATE_REQUESTED';
export const PROJECT_OPEN_REQUESTED = 'PROJECT_OPEN_REQUESTED';

export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_RENAME = 'PROJECT_RENAME';
export const PROJECT_OPEN = 'PROJECT_OPEN';
export const PROJECT_IMPORT = 'PROJECT_IMPORT';
export const PROJECT_OPEN_WORKSPACE = 'PROJECT_OPEN_WORKSPACE';
export const PROJECT_UPDATE_META = 'PROJECT_UPDATE_META';

export const NODE_ADD = 'NODE_ADD';
export const NODE_UPDATE_PROPERTY = 'NODE_UPDATE_PROPERTY';

export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_RESIZE = 'COMMENT_RESIZE';
export const COMMENT_SET_CONTENT = 'COMMENT_SET_CONTENT';

export const LINK_ADD = 'LINK_ADD';

export const BULK_MOVE_NODES_AND_COMMENTS = 'BULK_MOVE_NODES_AND_COMMENTS';
export const BULK_DELETE_ENTITIES = 'BULK_DELETE_ENTITIES';

export const PATCH_ADD = 'PATCH_ADD';
export const PATCH_RENAME = 'PATCH_RENAME';
export const PATCH_DELETE = 'PATCH_DELETE';
export const PATCH_DESCRIPTION_UPDATE = 'PATCH_DESCRIPTION_UPDATE';

export const PATCH_HISTORY_UNDO = 'PATCH_HISTORY_UNDO';
export const PATCH_HISTORY_REDO = 'PATCH_HISTORY_REDO';

export const SAVE_PROJECT = 'SAVE_PROJECT';
