export default {
  authors: [
    'Amperka team',
  ],
  description: '',
  license: '',
  name: 'Awesome project',
  patches: {
    '@/1': {
      impls: {},
      links: {},
      nodes: {},
      path: '@/1',
      pins: {},
    },
    '@/2': {
      impls: {},
      links: {},
      nodes: {},
      path: '@/2',
      pins: {},
    },
    'xod/core/and': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: e.inputs.a && e.inputs.b };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/and',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'boolean',
          value: false,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'boolean',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/any': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.a || e.inputs.b) {\n    return { out: PULSE };\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/any',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'pulse',
          value: false,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'pulse',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/blink': {
      impls: {},
      links: {
        BygxthGNqae: {
          id: 'BygxthGNqae',
          input: {
            nodeId: 'B1zOhGEqax',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'SJbd3z45ag',
            pinKey: 'state',
          },
        },
        'Hk-lY2MEcpl': {
          id: 'Hk-lY2MEcpl',
          input: {
            nodeId: 'Sye_2f45ax',
            pinKey: 'interval',
          },
          output: {
            nodeId: 'Sku3GVq6e',
            pinKey: '__out__',
          },
        },
        rkzlt2MVcTe: {
          id: 'rkzlt2MVcTe',
          input: {
            nodeId: 'SJbd3z45ag',
            pinKey: 'toggle',
          },
          output: {
            nodeId: 'Sye_2f45ax',
            pinKey: 'tick',
          },
        },
      },
      nodes: {
        B1zOhGEqax: {
          id: 'B1zOhGEqax',
          pins: {},
          position: {
            x: 263,
            y: 508,
          },
          type: 'xod/core/output-boolean',
        },
        SJbd3z45ag: {
          id: 'SJbd3z45ag',
          pins: {},
          position: {
            x: 271,
            y: 355,
          },
          type: 'xod/core/latch',
        },
        Sku3GVq6e: {
          id: 'Sku3GVq6e',
          pins: {},
          position: {
            x: 268,
            y: 103,
          },
          type: 'xod/core/input-number',
        },
        Sye_2f45ax: {
          id: 'Sye_2f45ax',
          pins: {
            interval: {
              curried: false,
              value: 1,
            },
          },
          position: {
            x: 267,
            y: 215,
          },
          type: 'xod/core/clock',
        },
      },
      path: 'xod/core/blink',
      pins: {
        B1zOhGEqax: {
          description: '',
          direction: 'output',
          key: 'B1zOhGEqax',
          label: 'B1zOhGEqax',
          order: 0,
          type: 'boolean',
          value: false,
        },
        Sku3GVq6e: {
          description: '',
          direction: 'input',
          key: 'Sku3GVq6e',
          label: 'Sku3GVq6e',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/both': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.a && e.inputs.b) {\n    return { out: PULSE };\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/both',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'pulse',
          value: false,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'pulse',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/button': {
      impls: {
        espruino: "\nmodule.exports.setup = function(e) {\n  var pin = new Pin(e.props.pin);\n\n  setWatch(function(evt) {\n    e.fire({ state: !evt.state });\n  }, pin, {\n    edge: 'both',\n    repeat: true,\n    debounce: 30\n  });\n};\n",
      },
      links: {},
      nodes: {},
      path: 'xod/core/button',
      pins: {
        state: {
          description: '',
          direction: 'output',
          key: 'state',
          label: 'state',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/buzzer': {
      impls: {
        espruino: '\nmodule.exports.setup = function(e) {\n  e.context.pin = new Pin(e.props.pin);\n};\n\nmodule.exports.evaluate = function(e) {\n  var f = e.inputs.freq;\n\n  if (f === 0) {\n    digitalWrite(e.context.pin, false);\n  } else {\n    analogWrite(e.context.pin, 0.5, { freq: f });\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/buzzer',
      pins: {
        freq: {
          description: '',
          direction: 'input',
          key: 'freq',
          label: 'freq',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/cast-boolean-to-number': {
      impls: {
        cpp: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    emitNumber(nid, Outputs::__OUT__, getLogic(nid, Inputs::__IN__));\n}\n',
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: Number(e.inputs.__in__) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-boolean-to-number',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'boolean',
          value: false,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/cast-boolean-to-pulse': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.__in__ === false) return;\n  return { __out__: PULSE };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-boolean-to-pulse',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'boolean',
          value: false,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/cast-boolean-to-string': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: String(e.inputs.__in__) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-boolean-to-string',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'boolean',
          value: false,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/cast-number-to-boolean': {
      impls: {
        cpp: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    emitLogic(nid, Outputs::__OUT__, getNumber(nid, Inputs::__IN__));\n}\n',
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: Boolean(e.inputs.__in__) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-number-to-boolean',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'number',
          value: 0,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/cast-number-to-pulse': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (Boolean(e.inputs.__in__) === false) return;\n\n  return { __out__: PULSE };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-number-to-pulse',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'number',
          value: 0,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/cast-number-to-string': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: String(e.inputs.__in__) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-number-to-string',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'number',
          value: 0,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/cast-pulse-to-boolean': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: true };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-pulse-to-boolean',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'pulse',
          value: false,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/cast-pulse-to-number': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: 1 };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-pulse-to-number',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'pulse',
          value: false,
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/cast-string-to-boolean': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { __out__: Boolean(e.inputs.__in__) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-string-to-boolean',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'string',
          value: '',
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/cast-string-to-pulse': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (Boolean(e.inputs.__in__) === false) return;\n\n  return { __out__: PULSE };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/cast-string-to-pulse',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'string',
          value: '',
        },
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/choose': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.x) {\n    return { truePulse: PULSE };\n  } else {\n    return { falsePulse: PULSE };\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/choose',
      pins: {
        falsePulse: {
          description: '',
          direction: 'output',
          key: 'falsePulse',
          label: 'falsePulse',
          order: 1,
          type: 'pulse',
          value: false,
        },
        truePulse: {
          description: '',
          direction: 'output',
          key: 'truePulse',
          label: 'truePulse',
          order: 0,
          type: 'pulse',
          value: false,
        },
        x: {
          description: '',
          direction: 'input',
          key: 'x',
          label: 'x',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/choose-range': {
      impls: {},
      links: {
        BJIgthfVqpx: {
          id: 'BJIgthfVqpx',
          input: {
            nodeId: 'BJHu2GV5al',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'r14dnfE9al',
            pinKey: 'truePulse',
          },
        },
        BkreYhfVc6e: {
          id: 'BkreYhfVc6e',
          input: {
            nodeId: 'r14dnfE9al',
            pinKey: 'x',
          },
          output: {
            nodeId: 'H1PuhzVcax',
            pinKey: 'out',
          },
        },
        HJXxthMN9Tg: {
          id: 'HJXxthMN9Tg',
          input: {
            nodeId: 'H1PuhzVcax',
            pinKey: 'b',
          },
          output: {
            nodeId: 'rk__hGVcpe',
            pinKey: '__out__',
          },
        },
        HyNgF3f45pg: {
          id: 'HyNgF3f45pg',
          input: {
            nodeId: 'H1PuhzVcax',
            pinKey: 'a',
          },
          output: {
            nodeId: 'rk7unMVqpx',
            pinKey: '__out__',
          },
        },
        S1Pxt3G45Te: {
          id: 'S1Pxt3G45Te',
          input: {
            nodeId: 'B1Iu3fV9pe',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'r14dnfE9al',
            pinKey: 'falsePulse',
          },
        },
      },
      nodes: {
        B1Iu3fV9pe: {
          id: 'B1Iu3fV9pe',
          pins: {},
          position: {
            x: 420,
            y: 482,
          },
          type: 'xod/core/output-pulse',
        },
        BJHu2GV5al: {
          id: 'BJHu2GV5al',
          pins: {},
          position: {
            x: 242,
            y: 486,
          },
          type: 'xod/core/output-pulse',
        },
        H1PuhzVcax: {
          id: 'H1PuhzVcax',
          pins: {},
          position: {
            x: 332,
            y: 251,
          },
          type: 'xod/core/less',
        },
        r14dnfE9al: {
          id: 'r14dnfE9al',
          pins: {},
          position: {
            x: 332,
            y: 336,
          },
          type: 'xod/core/choose',
        },
        rk7unMVqpx: {
          id: 'rk7unMVqpx',
          pins: {},
          position: {
            x: 226,
            y: 91,
          },
          type: 'xod/core/input-number',
        },
        rk__hGVcpe: {
          id: 'rk__hGVcpe',
          pins: {},
          position: {
            x: 460,
            y: 88,
          },
          type: 'xod/core/input-number',
        },
      },
      path: 'xod/core/choose-range',
      pins: {
        B1Iu3fV9pe: {
          description: '',
          direction: 'output',
          key: 'B1Iu3fV9pe',
          label: 'B1Iu3fV9pe',
          order: 1,
          type: 'pulse',
          value: false,
        },
        BJHu2GV5al: {
          description: '',
          direction: 'output',
          key: 'BJHu2GV5al',
          label: 'BJHu2GV5al',
          order: 0,
          type: 'pulse',
          value: false,
        },
        rk7unMVqpx: {
          description: '',
          direction: 'input',
          key: 'rk7unMVqpx',
          label: 'rk7unMVqpx',
          order: 0,
          type: 'number',
          value: 0,
        },
        rk__hGVcpe: {
          description: '',
          direction: 'input',
          key: 'rk__hGVcpe',
          label: 'rk__hGVcpe',
          order: 1,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/choose-range-2p': {
      impls: {},
      links: {
        H1alKhzEqpl: {
          id: 'H1alKhzEqpl',
          input: {
            nodeId: 'H1aOnfEcpe',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'rJWlOnGNqal',
            pinKey: 'BJHu2GV5al',
          },
        },
        H1jeF2MNcTg: {
          id: 'H1jeF2MNcTg',
          input: {
            nodeId: 'r1FO2fN5ag',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'BJiu3GNq6g',
            pinKey: 'B1Iu3fV9pe',
          },
        },
        H1xZYnGV56x: {
          id: 'H1xZYnGV56x',
          input: {
            nodeId: 'rygeO3zE5Te',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'SJ2u2zVqTe',
            pinKey: 'out',
          },
        },
        Sy9xthME56g: {
          id: 'Sy9xthME56g',
          input: {
            nodeId: 'rJWlOnGNqal',
            pinKey: 'rk7unMVqpx',
          },
          output: {
            nodeId: 'ByCO2fNqag',
            pinKey: '__out__',
          },
        },
        r1JbF3ME5Tx: {
          id: 'r1JbF3ME5Tx',
          input: {
            nodeId: 'SJ2u2zVqTe',
            pinKey: 'a',
          },
          output: {
            nodeId: 'rJWlOnGNqal',
            pinKey: 'B1Iu3fV9pe',
          },
        },
        r1_xF2fE9Tx: {
          id: 'r1_xF2fE9Tx',
          input: {
            nodeId: 'BJiu3GNq6g',
            pinKey: 'rk__hGVcpe',
          },
          output: {
            nodeId: 'rk1guhzVqpl',
            pinKey: '__out__',
          },
        },
        rJ0gY2G49px: {
          id: 'rJ0gY2G49px',
          input: {
            nodeId: 'SJ2u2zVqTe',
            pinKey: 'b',
          },
          output: {
            nodeId: 'BJiu3GNq6g',
            pinKey: 'BJHu2GV5al',
          },
        },
        rkKetnfN5al: {
          id: 'rkKetnfN5al',
          input: {
            nodeId: 'BJiu3GNq6g',
            pinKey: 'rk7unMVqpx',
          },
          output: {
            nodeId: 'ByCO2fNqag',
            pinKey: '__out__',
          },
        },
        ry2xt2M4c6e: {
          id: 'ry2xt2M4c6e',
          input: {
            nodeId: 'rJWlOnGNqal',
            pinKey: 'rk__hGVcpe',
          },
          output: {
            nodeId: 'BJqu3zV9ax',
            pinKey: '__out__',
          },
        },
      },
      nodes: {
        BJiu3GNq6g: {
          id: 'BJiu3GNq6g',
          pins: {},
          position: {
            x: 462,
            y: 256,
          },
          type: 'xod/core/choose-range',
        },
        BJqu3zV9ax: {
          id: 'BJqu3zV9ax',
          pins: {},
          position: {
            x: 367,
            y: 117,
          },
          type: 'xod/core/input-number',
        },
        ByCO2fNqag: {
          id: 'ByCO2fNqag',
          pins: {},
          position: {
            x: 189,
            y: 116,
          },
          type: 'xod/core/input-number',
        },
        H1aOnfEcpe: {
          id: 'H1aOnfEcpe',
          pins: {},
          position: {
            x: 191,
            y: 452,
          },
          type: 'xod/core/output-pulse',
        },
        SJ2u2zVqTe: {
          id: 'SJ2u2zVqTe',
          pins: {},
          position: {
            x: 382,
            y: 361,
          },
          type: 'xod/core/both',
        },
        r1FO2fN5ag: {
          id: 'r1FO2fN5ag',
          pins: {},
          position: {
            x: 554,
            y: 457,
          },
          type: 'xod/core/output-pulse',
        },
        rJWlOnGNqal: {
          id: 'rJWlOnGNqal',
          pins: {},
          position: {
            x: 271,
            y: 258,
          },
          type: 'xod/core/choose-range',
        },
        rk1guhzVqpl: {
          id: 'rk1guhzVqpl',
          pins: {},
          position: {
            x: 553,
            y: 118,
          },
          type: 'xod/core/input-number',
        },
        rygeO3zE5Te: {
          id: 'rygeO3zE5Te',
          pins: {},
          position: {
            x: 402,
            y: 456,
          },
          type: 'xod/core/output-pulse',
        },
      },
      path: 'xod/core/choose-range-2p',
      pins: {
        BJqu3zV9ax: {
          description: '',
          direction: 'input',
          key: 'BJqu3zV9ax',
          label: 'BJqu3zV9ax',
          order: 1,
          type: 'number',
          value: 0,
        },
        ByCO2fNqag: {
          description: '',
          direction: 'input',
          key: 'ByCO2fNqag',
          label: 'ByCO2fNqag',
          order: 0,
          type: 'number',
          value: 0,
        },
        H1aOnfEcpe: {
          description: '',
          direction: 'output',
          key: 'H1aOnfEcpe',
          label: 'H1aOnfEcpe',
          order: 0,
          type: 'pulse',
          value: false,
        },
        r1FO2fN5ag: {
          description: '',
          direction: 'output',
          key: 'r1FO2fN5ag',
          label: 'r1FO2fN5ag',
          order: 2,
          type: 'pulse',
          value: false,
        },
        rk1guhzVqpl: {
          description: '',
          direction: 'input',
          key: 'rk1guhzVqpl',
          label: 'rk1guhzVqpl',
          order: 2,
          type: 'number',
          value: 0,
        },
        rygeO3zE5Te: {
          description: '',
          direction: 'output',
          key: 'rygeO3zE5Te',
          label: 'rygeO3zE5Te',
          order: 1,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/choose-range-3p': {
      impls: {},
      links: {
        'B1O-F2zN56g': {
          id: 'B1O-F2zN56g',
          input: {
            nodeId: 'HycgdhfNqpe',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'Skog_nME5Tg',
            pinKey: 'B1Iu3fV9pe',
          },
        },
        BJXbt3fVcae: {
          id: 'BJXbt3fVcae',
          input: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'rk1guhzVqpl',
          },
          output: {
            nodeId: 'HkVeOnzV9ae',
            pinKey: '__out__',
          },
        },
        BkUbF2zE9ax: {
          id: 'BkUbF2zE9ax',
          input: {
            nodeId: 'Skog_nME5Tg',
            pinKey: 'rk__hGVcpe',
          },
          output: {
            nodeId: 'ByHe_hGEc6l',
            pinKey: '__out__',
          },
        },
        BkbZK2zN9pe: {
          id: 'BkbZK2zN9pe',
          input: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'ByCO2fNqag',
          },
          output: {
            nodeId: 'Skfg_nfE5pg',
            pinKey: '__out__',
          },
        },
        BkwZthfE9al: {
          id: 'BkwZthfE9al',
          input: {
            nodeId: 'Skog_nME5Tg',
            pinKey: 'rk7unMVqpx',
          },
          output: {
            nodeId: 'Skfg_nfE5pg',
            pinKey: '__out__',
          },
        },
        H1MWKhGNqTx: {
          id: 'H1MWKhGNqTx',
          input: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'BJqu3zV9ax',
          },
          output: {
            nodeId: 'BJXxO2zVqpx',
            pinKey: '__out__',
          },
        },
        HJBZKnMEqae: {
          id: 'HJBZKnMEqae',
          input: {
            nodeId: 'B1_x_3G4q6x',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'rygeO3zE5Te',
          },
        },
        S1KZY2MN96l: {
          id: 'S1KZY2MN96l',
          input: {
            nodeId: 'S12ld3MNcax',
            pinKey: 'a',
          },
          output: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'r1FO2fN5ag',
          },
        },
        'Sy5-YnzEq6e': {
          id: 'Sy5-YnzEq6e',
          input: {
            nodeId: 'S12ld3MNcax',
            pinKey: 'b',
          },
          output: {
            nodeId: 'Skog_nME5Tg',
            pinKey: 'BJHu2GV5al',
          },
        },
        rkiWt3MV9Tx: {
          id: 'rkiWt3MV9Tx',
          input: {
            nodeId: 'BkFxdnzNcpg',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'S12ld3MNcax',
            pinKey: 'out',
          },
        },
        ryNWFhGEqag: {
          id: 'ryNWFhGEqag',
          input: {
            nodeId: 'Hkwedhz456l',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'Hy8eu3MNqTl',
            pinKey: 'H1aOnfEcpe',
          },
        },
      },
      nodes: {
        B1_x_3G4q6x: {
          id: 'B1_x_3G4q6x',
          pins: {},
          position: {
            x: 313,
            y: 538,
          },
          type: 'xod/core/output-pulse',
        },
        BJXxO2zVqpx: {
          id: 'BJXxO2zVqpx',
          pins: {},
          position: {
            x: 315,
            y: 140,
          },
          type: 'xod/core/input-number',
        },
        BkFxdnzNcpg: {
          id: 'BkFxdnzNcpg',
          pins: {},
          position: {
            x: 456,
            y: 535,
          },
          type: 'xod/core/output-pulse',
        },
        ByHe_hGEc6l: {
          id: 'ByHe_hGEc6l',
          pins: {},
          position: {
            x: 589,
            y: 140,
          },
          type: 'xod/core/input-number',
        },
        HkVeOnzV9ae: {
          id: 'HkVeOnzV9ae',
          pins: {},
          position: {
            x: 452,
            y: 140,
          },
          type: 'xod/core/input-number',
        },
        Hkwedhz456l: {
          id: 'Hkwedhz456l',
          pins: {},
          position: {
            x: 171,
            y: 538,
          },
          type: 'xod/core/output-pulse',
        },
        Hy8eu3MNqTl: {
          id: 'Hy8eu3MNqTl',
          pins: {},
          position: {
            x: 249,
            y: 294,
          },
          type: 'xod/core/choose-range-2p',
        },
        HycgdhfNqpe: {
          id: 'HycgdhfNqpe',
          pins: {},
          position: {
            x: 598,
            y: 533,
          },
          type: 'xod/core/output-pulse',
        },
        S12ld3MNcax: {
          id: 'S12ld3MNcax',
          pins: {},
          position: {
            x: 419,
            y: 405,
          },
          type: 'xod/core/both',
        },
        Skfg_nfE5pg: {
          id: 'Skfg_nfE5pg',
          pins: {},
          position: {
            x: 173,
            y: 140,
          },
          type: 'xod/core/input-number',
        },
        Skog_nME5Tg: {
          id: 'Skog_nME5Tg',
          pins: {},
          position: {
            x: 495,
            y: 297,
          },
          type: 'xod/core/choose-range',
        },
      },
      path: 'xod/core/choose-range-3p',
      pins: {
        B1_x_3G4q6x: {
          description: '',
          direction: 'output',
          key: 'B1_x_3G4q6x',
          label: 'B1_x_3G4q6x',
          order: 1,
          type: 'pulse',
          value: false,
        },
        BJXxO2zVqpx: {
          description: '',
          direction: 'input',
          key: 'BJXxO2zVqpx',
          label: 'BJXxO2zVqpx',
          order: 1,
          type: 'number',
          value: 0,
        },
        BkFxdnzNcpg: {
          description: '',
          direction: 'output',
          key: 'BkFxdnzNcpg',
          label: 'BkFxdnzNcpg',
          order: 2,
          type: 'pulse',
          value: false,
        },
        ByHe_hGEc6l: {
          description: '',
          direction: 'input',
          key: 'ByHe_hGEc6l',
          label: 'ByHe_hGEc6l',
          order: 3,
          type: 'number',
          value: 0,
        },
        HkVeOnzV9ae: {
          description: '',
          direction: 'input',
          key: 'HkVeOnzV9ae',
          label: 'HkVeOnzV9ae',
          order: 2,
          type: 'number',
          value: 0,
        },
        Hkwedhz456l: {
          description: '',
          direction: 'output',
          key: 'Hkwedhz456l',
          label: 'Hkwedhz456l',
          order: 0,
          type: 'pulse',
          value: false,
        },
        HycgdhfNqpe: {
          description: '',
          direction: 'output',
          key: 'HycgdhfNqpe',
          label: 'HycgdhfNqpe',
          order: 3,
          type: 'pulse',
          value: false,
        },
        Skfg_nfE5pg: {
          description: '',
          direction: 'input',
          key: 'Skfg_nfE5pg',
          label: 'Skfg_nfE5pg',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/clock': {
      impls: {
        cpp: 'struct State {\n    TimeMs nextTrig;\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    TimeMs tNow = transactionTime();\n    TimeMs dt = getNumber(nid, Inputs::IVAL) * 1000;\n    TimeMs tNext = tNow + dt;\n\n    if (isInputDirty(nid, Inputs::IVAL)) {\n        if (dt == 0) {\n            state->nextTrig = 0;\n            clearTimeout(nid);\n        } else if (state->nextTrig < tNow || state->nextTrig > tNext) {\n            state->nextTrig = tNext;\n            setTimeout(nid, dt);\n        }\n    } else {\n        // It was a scheduled tick\n        emitLogic(nid, Outputs::TICK, 1);\n        state->nextTrig = tNext;\n        setTimeout(nid, dt);\n    }\n}\n',
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.context.intervalID) {\n    clearInterval(e.context.intervalID);\n  }\n\n  e.context.intervalID = setInterval(function() {\n    e.fire({ tick: PULSE });\n  }, e.inputs.interval * 1000);\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/clock',
      pins: {
        interval: {
          description: '',
          direction: 'input',
          key: 'interval',
          label: 'interval',
          order: 0,
          type: 'number',
          value: 0,
        },
        tick: {
          description: '',
          direction: 'output',
          key: 'tick',
          label: 'tick',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/compare': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var a = e.inputs.a;\n  var b = e.inputs.b;\n  if (a < b) {\n    return { less: PULSE };\n  } else if (a > b) {\n    return { greater: PULSE };\n  } else {\n    return { equal: PULSE };\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/compare',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        equal: {
          description: '',
          direction: 'output',
          key: 'equal',
          label: 'equal',
          order: 0,
          type: 'pulse',
          value: false,
        },
        greater: {
          description: '',
          direction: 'output',
          key: 'greater',
          label: 'greater',
          order: 2,
          type: 'pulse',
          value: false,
        },
        less: {
          description: '',
          direction: 'output',
          key: 'less',
          label: 'less',
          order: 1,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/concat': {
      impls: {
        js: 'module.exports.evaluate = function(e) {\n  return { result: (String(e.inputs.a) + String(e.inputs.b)) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/concat',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'string',
          value: '',
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'string',
          value: '',
        },
        result: {
          description: '',
          direction: 'output',
          key: 'result',
          label: 'result',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/const-bool': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { value: e.inputs.inValue };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/const-bool',
      pins: {
        inValue: {
          description: '',
          direction: 'input',
          key: 'inValue',
          label: 'inValue',
          order: 0,
          type: 'boolean',
          value: false,
        },
        pulse: {
          description: '',
          direction: 'input',
          key: 'pulse',
          label: 'pulse',
          order: 1,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/const-number': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { value: e.inputs.inValue };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/const-number',
      pins: {
        inValue: {
          description: '',
          direction: 'input',
          key: 'inValue',
          label: 'inValue',
          order: 0,
          type: 'number',
          value: 0,
        },
        pulse: {
          description: '',
          direction: 'input',
          key: 'pulse',
          label: 'pulse',
          order: 1,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/const-string': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { value: e.inputs.inValue };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/const-string',
      pins: {
        inValue: {
          description: '',
          direction: 'input',
          key: 'inValue',
          label: 'inValue',
          order: 0,
          type: 'string',
          value: '',
        },
        pulse: {
          description: '',
          direction: 'input',
          key: 'pulse',
          label: 'pulse',
          order: 1,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/constant-logic': {
      impls: {
        cpp: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    reemitLogic(nid, Outputs::VAL);\n}\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/constant-logic',
      pins: {
        VAL: {
          description: '',
          direction: 'output',
          key: 'VAL',
          label: 'VAL',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/constant-number': {
      impls: {
        cpp: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    reemitNumber(nid, Outputs::VAL);\n}\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/constant-number',
      pins: {
        VAL: {
          description: '',
          direction: 'output',
          key: 'VAL',
          label: 'VAL',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/digital-input': {
      impls: {
        espruino: "\nmodule.exports.setup = function(e) {\n  e.inputs.pin = new Pin(e.inputs.pin);\n\n  setWatch(function(evt) {\n    e.fire({ state: !evt.state });\n  }, e.inputs.pin, {\n    edge: 'both',\n    repeat: true,\n    debounce: 30\n  });\n};\n",
      },
      links: {},
      nodes: {},
      path: 'xod/core/digital-input',
      pins: {
        PIN: {
          description: '',
          direction: 'input',
          key: 'PIN',
          label: 'pin',
          order: 0,
          type: 'string',
          value: '',
        },
        VALUE: {
          description: '',
          direction: 'output',
          key: 'VALUE',
          label: 'value',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/digital-output': {
      impls: {
        arduino: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    const int pin = (int)getNumber(nid, Inputs::PIN);\n    const bool val = getLogic(nid, Inputs::VALUE);\n\n    if (isInputDirty(nid, Inputs::PIN)) {\n        ::pinMode(pin, OUTPUT);\n    }\n\n    ::digitalWrite(pin, val);\n}\n',
        espruino: '\nmodule.exports.evaluate = function(e) {\n  digitalWrite(e.inputs.pin, e.inputs.value);\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/digital-output',
      pins: {
        PIN: {
          description: '',
          direction: 'input',
          key: 'PIN',
          label: 'pin',
          order: 0,
          type: 'number',
          value: 0,
        },
        VALUE: {
          description: '',
          direction: 'input',
          key: 'VALUE',
          label: 'value',
          order: 1,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/either': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var out = e.inputs.inp ? e.inputs.trueValue : e.inputs.falseValue;\n  return { out: out };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/either',
      pins: {
        falseValue: {
          description: '',
          direction: 'input',
          key: 'falseValue',
          label: 'falseValue',
          order: 2,
          type: 'number',
          value: 0,
        },
        inp: {
          description: '',
          direction: 'input',
          key: 'inp',
          label: 'inp',
          order: 0,
          type: 'boolean',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
        trueValue: {
          description: '',
          direction: 'input',
          key: 'trueValue',
          label: 'trueValue',
          order: 1,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/equal': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var a = e.inputs.a;\n  var b = e.inputs.b;\n\n  if (a === undefined || b === undefined) {\n    return;\n  }\n\n  return { out: a === b };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/equal',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/file-read': {
      impls: {
        nodejs: "var path = require('path');\nvar fs = require('fs');\n\nmodule.exports.evaluate = function(e) {\n  var filename = e.inputs.fileName;\n\n  fs.readFile(filename, function (err, data) {\n    if (err) {\n      e.fire({ error: err.toString() });\n      return;\n    }\n\n    e.fire({ data: data });\n  });\n};\n",
      },
      links: {},
      nodes: {},
      path: 'xod/core/file-read',
      pins: {
        data: {
          description: '',
          direction: 'output',
          key: 'data',
          label: 'data',
          order: 0,
          type: 'string',
          value: '',
        },
        error: {
          description: '',
          direction: 'output',
          key: 'error',
          label: 'error',
          order: 1,
          type: 'string',
          value: '',
        },
        fileName: {
          description: '',
          direction: 'input',
          key: 'fileName',
          label: 'fileName',
          order: 0,
          type: 'string',
          value: '',
        },
        pulse: {
          description: '',
          direction: 'input',
          key: 'pulse',
          label: 'pulse',
          order: 1,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/file-write': {
      impls: {
        nodejs: "var path = require('path');\nvar fs = require('fs');\n\nmodule.exports.evaluate = function(e) {\n  var filename = e.inputs.fileName;\n  var data = e.inputs.data;\n\n  fs.writeFile(filename, data, function (err) {\n    if (err) {\n      e.fire({ onFailure: err.toString() });\n      return;\n    }\n\n    e.fire({ onSuccess: PULSE });\n  });\n};\n",
      },
      links: {},
      nodes: {},
      path: 'xod/core/file-write',
      pins: {
        data: {
          description: '',
          direction: 'input',
          key: 'data',
          label: 'data',
          order: 1,
          type: 'pulse',
          value: false,
        },
        fileName: {
          description: '',
          direction: 'input',
          key: 'fileName',
          label: 'fileName',
          order: 0,
          type: 'string',
          value: '',
        },
        onFailure: {
          description: '',
          direction: 'output',
          key: 'onFailure',
          label: 'onFailure',
          order: 1,
          type: 'string',
          value: '',
        },
        onSuccess: {
          description: '',
          direction: 'output',
          key: 'onSuccess',
          label: 'onSuccess',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/greater': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var a = e.inputs.a;\n  var b = e.inputs.b;\n\n  if (a === undefined || b === undefined) {\n    return;\n  }\n\n  return { out: a > b };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/greater',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/greater-equal': {
      impls: {},
      links: {
        BykfK2G49Tx: {
          id: 'BykfK2G49Tx',
          input: {
            nodeId: 'SJb-u2f4qal',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'B1lWO3G4qag',
            pinKey: 'out',
          },
        },
        HJ6bYhfEcTl: {
          id: 'HJ6bYhfEcTl',
          input: {
            nodeId: 'H1k-d3zN9ae',
            pinKey: 'b',
          },
          output: {
            nodeId: 'r10lu2MVq6g',
            pinKey: '__out__',
          },
        },
        HJRWt3MV56l: {
          id: 'HJRWt3MV56l',
          input: {
            nodeId: 'B1lWO3G4qag',
            pinKey: 'in',
          },
          output: {
            nodeId: 'H1k-d3zN9ae',
            pinKey: 'out',
          },
        },
        SynbFhfE9px: {
          id: 'SynbFhfE9px',
          input: {
            nodeId: 'H1k-d3zN9ae',
            pinKey: 'a',
          },
          output: {
            nodeId: 'HJ6gO2fVcpx',
            pinKey: '__out__',
          },
        },
      },
      nodes: {
        B1lWO3G4qag: {
          id: 'B1lWO3G4qag',
          pins: {},
          position: {
            x: 360,
            y: 358,
          },
          type: 'xod/core/not',
        },
        'H1k-d3zN9ae': {
          id: 'H1k-d3zN9ae',
          pins: {},
          position: {
            x: 353,
            y: 249,
          },
          type: 'xod/core/less',
        },
        HJ6gO2fVcpx: {
          id: 'HJ6gO2fVcpx',
          pins: {},
          position: {
            x: 271,
            y: 122,
          },
          type: 'xod/core/input-number',
        },
        'SJb-u2f4qal': {
          id: 'SJb-u2f4qal',
          pins: {},
          position: {
            x: 360,
            y: 479,
          },
          type: 'xod/core/output-boolean',
        },
        r10lu2MVq6g: {
          id: 'r10lu2MVq6g',
          pins: {},
          position: {
            x: 439,
            y: 120,
          },
          type: 'xod/core/input-number',
        },
      },
      path: 'xod/core/greater-equal',
      pins: {
        HJ6gO2fVcpx: {
          description: '',
          direction: 'input',
          key: 'HJ6gO2fVcpx',
          label: 'HJ6gO2fVcpx',
          order: 0,
          type: 'number',
          value: 0,
        },
        'SJb-u2f4qal': {
          description: '',
          direction: 'output',
          key: 'SJb-u2f4qal',
          label: 'SJb-u2f4qal',
          order: 0,
          type: 'boolean',
          value: false,
        },
        r10lu2MVq6g: {
          description: '',
          direction: 'input',
          key: 'r10lu2MVq6g',
          label: 'r10lu2MVq6g',
          order: 1,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/in-range': {
      impls: {},
      links: {
        BJgMYhMEqpx: {
          id: 'BJgMYhMEqpx',
          input: {
            nodeId: 'HJrb_nz4qTx',
            pinKey: 'HJ6gO2fVcpx',
          },
          output: {
            nodeId: 'BJGbOnfE5pl',
            pinKey: '__out__',
          },
        },
        BkrMYhzV9ax: {
          id: 'BkrMYhzV9ax',
          input: {
            nodeId: 'HywZO2zE9ag',
            pinKey: 'b',
          },
          output: {
            nodeId: 'HJIZ_2f4qag',
            pinKey: 'out',
          },
        },
        SJWMK3fN5pg: {
          id: 'SJWMK3fN5pg',
          input: {
            nodeId: 'HJrb_nz4qTx',
            pinKey: 'r10lu2MVq6g',
          },
          output: {
            nodeId: 'SymbO3GNcal',
            pinKey: '__out__',
          },
        },
        rJNGK3f49ax: {
          id: 'rJNGK3f49ax',
          input: {
            nodeId: 'HywZO2zE9ag',
            pinKey: 'a',
          },
          output: {
            nodeId: 'HJrb_nz4qTx',
            pinKey: 'SJb-u2f4qal',
          },
        },
        rJmMF3GEqae: {
          id: 'rJmMF3GEqae',
          input: {
            nodeId: 'HJIZ_2f4qag',
            pinKey: 'b',
          },
          output: {
            nodeId: 'HJVZ_2GEcpe',
            pinKey: '__out__',
          },
        },
        rkzfY2GE9al: {
          id: 'rkzfY2GE9al',
          input: {
            nodeId: 'HJIZ_2f4qag',
            pinKey: 'a',
          },
          output: {
            nodeId: 'BJGbOnfE5pl',
            pinKey: '__out__',
          },
        },
        ry8zYhMN5px: {
          id: 'ry8zYhMN5px',
          input: {
            nodeId: 'Hy_bd3MNcax',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'HywZO2zE9ag',
            pinKey: 'out',
          },
        },
      },
      nodes: {
        BJGbOnfE5pl: {
          id: 'BJGbOnfE5pl',
          pins: {},
          position: {
            x: 241,
            y: 117,
          },
          type: 'xod/core/input-number',
        },
        HJIZ_2f4qag: {
          id: 'HJIZ_2f4qag',
          pins: {},
          position: {
            x: 520,
            y: 271,
          },
          type: 'xod/core/less',
        },
        HJVZ_2GEcpe: {
          id: 'HJVZ_2GEcpe',
          pins: {},
          position: {
            x: 595,
            y: 116,
          },
          type: 'xod/core/input-number',
        },
        HJrb_nz4qTx: {
          id: 'HJrb_nz4qTx',
          pins: {},
          position: {
            x: 349,
            y: 270,
          },
          type: 'xod/core/greater-equal',
        },
        Hy_bd3MNcax: {
          id: 'Hy_bd3MNcax',
          pins: {},
          position: {
            x: 432,
            y: 541,
          },
          type: 'xod/core/output-boolean',
        },
        HywZO2zE9ag: {
          id: 'HywZO2zE9ag',
          pins: {},
          position: {
            x: 432,
            y: 407,
          },
          type: 'xod/core/and',
        },
        SymbO3GNcal: {
          id: 'SymbO3GNcal',
          pins: {},
          position: {
            x: 434,
            y: 114,
          },
          type: 'xod/core/input-number',
        },
      },
      path: 'xod/core/in-range',
      pins: {
        BJGbOnfE5pl: {
          description: '',
          direction: 'input',
          key: 'BJGbOnfE5pl',
          label: 'BJGbOnfE5pl',
          order: 0,
          type: 'number',
          value: 0,
        },
        HJVZ_2GEcpe: {
          description: '',
          direction: 'input',
          key: 'HJVZ_2GEcpe',
          label: 'HJVZ_2GEcpe',
          order: 2,
          type: 'number',
          value: 0,
        },
        Hy_bd3MNcax: {
          description: '',
          direction: 'output',
          key: 'Hy_bd3MNcax',
          label: 'Hy_bd3MNcax',
          order: 0,
          type: 'boolean',
          value: false,
        },
        SymbO3GNcal: {
          description: '',
          direction: 'input',
          key: 'SymbO3GNcal',
          label: 'SymbO3GNcal',
          order: 1,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/input-bool': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/input-bool',
      pins: {
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/input-boolean': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/input-boolean',
      pins: {
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/input-number': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/input-number',
      pins: {
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/input-pulse': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/input-pulse',
      pins: {
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/input-string': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/input-string',
      pins: {
        __out__: {
          description: '',
          direction: 'output',
          key: '__out__',
          label: '__out__',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/latch': {
      impls: {
        cpp: 'struct State {\n    bool value;\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    if (isInputDirty(nid, Inputs::RST)) {\n        state->value = false;\n    } else if (isInputDirty(nid, Inputs::SET)) {\n        state->value = true;\n    } else {\n        state->value = !state->value;\n    }\n\n    emitLogic(nid, Outputs::OUT, state->value);\n}\n',
        js: '\nmodule.exports.evaluate = function(e) {\n  var inputs = e.inputs;\n  var newState;\n\n  if (inputs.toggle) {\n    newState = !e.context.state;\n  } else if (inputs.set) {\n    newState = true;\n  } else /* if (inputs.reset) */ {\n    newState = false;\n  }\n\n  e.context.state = newState;\n  return { state: newState };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/latch',
      pins: {
        reset: {
          description: '',
          direction: 'input',
          key: 'reset',
          label: 'reset',
          order: 2,
          type: 'pulse',
          value: false,
        },
        set: {
          description: '',
          direction: 'input',
          key: 'set',
          label: 'set',
          order: 1,
          type: 'pulse',
          value: false,
        },
        state: {
          description: '',
          direction: 'output',
          key: 'state',
          label: 'state',
          order: 0,
          type: 'boolean',
          value: false,
        },
        toggle: {
          description: '',
          direction: 'input',
          key: 'toggle',
          label: 'toggle',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/led': {
      impls: {
        espruino: '\nmodule.exports.setup = function(e) {\n  e.context.pin = new Pin(e.props.pin);\n};\n\nmodule.exports.evaluate = function(e) {\n  var b = e.inputs.brightness;\n\n  // Adjust duty cycle as a power function to align brightness\n  // perception by human eye\n  var duty = b * b * b;\n\n  analogWrite(e.context.pin, duty);\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/led',
      pins: {
        brightness: {
          description: '',
          direction: 'input',
          key: 'brightness',
          label: 'brightness',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/led-new': {
      impls: {},
      links: {
        B1izYnz49Te: {
          id: 'B1izYnz49Te',
          input: {
            nodeId: 'rymFnzNcTe',
            pinKey: 'pin',
          },
          output: {
            nodeId: 'HJfKnfVcpe',
            pinKey: '__out__',
          },
        },
        BJqMF3ME5pe: {
          id: 'BJqMF3ME5pe',
          input: {
            nodeId: 'rymFnzNcTe',
            pinKey: 'value',
          },
          output: {
            nodeId: 'HylFhM45pg',
            pinKey: 'out',
          },
        },
        HkuzYhfE5Tg: {
          id: 'HkuzYhfE5Tg',
          input: {
            nodeId: 'HylFhM45pg',
            pinKey: 'b',
          },
          output: {
            nodeId: 'HJWF2fNq6l',
            pinKey: '__out__',
          },
        },
        SJtMY3ME9Tx: {
          id: 'SJtMY3ME9Tx',
          input: {
            nodeId: 'HylFhM45pg',
            pinKey: 'a',
          },
          output: {
            nodeId: 'SJKhfEqTl',
            pinKey: 'out',
          },
        },
        r13MK3M4cal: {
          id: 'r13MK3M4cal',
          input: {
            nodeId: 'SJKhfEqTl',
            pinKey: 'b',
          },
          output: {
            nodeId: 'HJWF2fNq6l',
            pinKey: '__out__',
          },
        },
        rkvMF3zEq6g: {
          id: 'rkvMF3zEq6g',
          input: {
            nodeId: 'SJKhfEqTl',
            pinKey: 'a',
          },
          output: {
            nodeId: 'HJWF2fNq6l',
            pinKey: '__out__',
          },
        },
      },
      nodes: {
        HJWF2fNq6l: {
          id: 'HJWF2fNq6l',
          pins: {},
          position: {
            x: 418,
            y: 104,
          },
          type: 'xod/core/input-number',
        },
        HJfKnfVcpe: {
          id: 'HJfKnfVcpe',
          pins: {},
          position: {
            x: 172,
            y: 104,
          },
          type: 'xod/core/input-number',
        },
        HylFhM45pg: {
          id: 'HylFhM45pg',
          pins: {},
          position: {
            x: 453,
            y: 298,
          },
          type: 'xod/math/multiply',
        },
        SJKhfEqTl: {
          id: 'SJKhfEqTl',
          pins: {},
          position: {
            x: 354,
            y: 218,
          },
          type: 'xod/math/multiply',
        },
        rymFnzNcTe: {
          id: 'rymFnzNcTe',
          pins: {
            pin: {
              curried: false,
            },
          },
          position: {
            x: 305,
            y: 430,
          },
          type: 'xod/core/digital-output',
        },
      },
      path: 'xod/core/led-new',
      pins: {
        HJWF2fNq6l: {
          description: '',
          direction: 'input',
          key: 'HJWF2fNq6l',
          label: 'HJWF2fNq6l',
          order: 1,
          type: 'number',
          value: 0,
        },
        HJfKnfVcpe: {
          description: '',
          direction: 'input',
          key: 'HJfKnfVcpe',
          label: 'HJfKnfVcpe',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/less': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var a = e.inputs.a;\n  var b = e.inputs.b;\n\n  if (a === undefined || b === undefined) {\n    return;\n  }\n\n  return { out: a < b };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/less',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/less-equal': {
      impls: {},
      links: {
        B1lQKhzN5al: {
          id: 'B1lQKhzN5al',
          input: {
            nodeId: 'HkUt2MV5pg',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'SJuYhM49pg',
            pinKey: 'out',
          },
        },
        Bk6MKhMNqpl: {
          id: 'Bk6MKhMNqpl',
          input: {
            nodeId: 'rkDFhMV5Te',
            pinKey: 'a',
          },
          output: {
            nodeId: 'BJNtnM45al',
            pinKey: '__out__',
          },
        },
        By1QF3fNc6l: {
          id: 'By1QF3fNc6l',
          input: {
            nodeId: 'SJuYhM49pg',
            pinKey: 'in',
          },
          output: {
            nodeId: 'rkDFhMV5Te',
            pinKey: 'out',
          },
        },
        rkRzthMN5Tg: {
          id: 'rkRzthMN5Tg',
          input: {
            nodeId: 'rkDFhMV5Te',
            pinKey: 'b',
          },
          output: {
            nodeId: 'ByrK2zNq6e',
            pinKey: '__out__',
          },
        },
      },
      nodes: {
        BJNtnM45al: {
          id: 'BJNtnM45al',
          pins: {},
          position: {
            x: 232,
            y: 76,
          },
          type: 'xod/core/input-number',
        },
        ByrK2zNq6e: {
          id: 'ByrK2zNq6e',
          pins: {},
          position: {
            x: 428,
            y: 78,
          },
          type: 'xod/core/input-number',
        },
        HkUt2MV5pg: {
          id: 'HkUt2MV5pg',
          pins: {},
          position: {
            x: 320,
            y: 454,
          },
          type: 'xod/core/output-boolean',
        },
        SJuYhM49pg: {
          id: 'SJuYhM49pg',
          pins: {},
          position: {
            x: 324,
            y: 318,
          },
          type: 'xod/core/not',
        },
        rkDFhMV5Te: {
          id: 'rkDFhMV5Te',
          pins: {},
          position: {
            x: 326,
            y: 196,
          },
          type: 'xod/core/greater',
        },
      },
      path: 'xod/core/less-equal',
      pins: {
        BJNtnM45al: {
          description: '',
          direction: 'input',
          key: 'BJNtnM45al',
          label: 'BJNtnM45al',
          order: 0,
          type: 'number',
          value: 0,
        },
        ByrK2zNq6e: {
          description: '',
          direction: 'input',
          key: 'ByrK2zNq6e',
          label: 'ByrK2zNq6e',
          order: 1,
          type: 'number',
          value: 0,
        },
        HkUt2MV5pg: {
          description: '',
          direction: 'output',
          key: 'HkUt2MV5pg',
          label: 'HkUt2MV5pg',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/map': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  var inputs = e.inputs;\n  var k = (inputs.inp - inputs.inA) / (inputs.inB - inputs.inA);\n  var out = inputs.outA + k * (inputs.outB - inputs.outA);\n\n  if (inputs.clip) {\n    if (inputs.outB > inputs.outA) {\n      out = Math.max(inputs.outA, out);\n      out = Math.min(inputs.outB, out);\n    } else {\n      out = Math.max(inputs.outB, out);\n      out = Math.min(inputs.outA, out);\n    }\n  }\n\n  return { out: out };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/map',
      pins: {
        clip: {
          description: '',
          direction: 'input',
          key: 'clip',
          label: 'clip',
          order: 5,
          type: 'boolean',
          value: false,
        },
        inA: {
          description: '',
          direction: 'input',
          key: 'inA',
          label: 'inA',
          order: 1,
          type: 'number',
          value: 0,
        },
        inB: {
          description: '',
          direction: 'input',
          key: 'inB',
          label: 'inB',
          order: 2,
          type: 'number',
          value: 0,
        },
        inp: {
          description: '',
          direction: 'input',
          key: 'inp',
          label: 'inp',
          order: 0,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
        outA: {
          description: '',
          direction: 'input',
          key: 'outA',
          label: 'outA',
          order: 3,
          type: 'number',
          value: 0,
        },
        outB: {
          description: '',
          direction: 'input',
          key: 'outB',
          label: 'outB',
          order: 4,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/not': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: !e.inputs.in };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/not',
      pins: {
        in: {
          description: '',
          direction: 'input',
          key: 'in',
          label: 'in',
          order: 0,
          type: 'boolean',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/or': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: e.inputs.a || e.inputs.b };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/or',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'boolean',
          value: false,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'boolean',
          value: false,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/output-boolean': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/output-boolean',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'boolean',
          value: false,
        },
      },
    },
    'xod/core/output-number': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/output-number',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/output-pulse': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/output-pulse',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/output-string': {
      impls: {},
      links: {},
      nodes: {},
      path: 'xod/core/output-string',
      pins: {
        __in__: {
          description: '',
          direction: 'input',
          key: '__in__',
          label: '__in__',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/pot': {
      impls: {
        espruino: '\nmodule.exports.setup = function(e) {\n  e.context.pin = new Pin(e.props.pin);\n};\n\nmodule.exports.evaluate = function(e) {\n  return { value: analogRead(e.context.pin) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/pot',
      pins: {
        sample: {
          description: '',
          direction: 'input',
          key: 'sample',
          label: 'sample',
          order: 0,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/servo': {
      impls: {
        espruino: '\nmodule.exports.setup = function(e) {\n  e.context.pin = new Pin(e.props.pin);\n};\n\nmodule.exports.evaluate = function(e) {\n  var minPulse = +e.props.minPulse;\n  var maxPulse = +e.props.maxPulse;\n  var us = minPulse + (maxPulse - minPulse) * e.inputs.value;\n  analogWrite(e.context.pin, us / 20000, { freq: 50 });\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/servo',
      pins: {
        maxPulse: {
          description: '',
          direction: 'input',
          key: 'maxPulse',
          label: 'maxPulse',
          order: 1,
          type: 'number',
          value: 0,
        },
        minPulse: {
          description: '',
          direction: 'input',
          key: 'minPulse',
          label: 'minPulse',
          order: 0,
          type: 'number',
          value: 0,
        },
        value: {
          description: '',
          direction: 'input',
          key: 'value',
          label: 'value',
          order: 2,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/sort-pair': {
      impls: {},
      links: {
        B17mF3zEcTg: {
          id: 'B17mF3zEcTg',
          input: {
            nodeId: 'BJ6KhzV5Te',
            pinKey: 'inp',
          },
          output: {
            nodeId: 'BkyeKhzV56l',
            pinKey: 'out',
          },
        },
        H1PXY2fE5pe: {
          id: 'H1PXY2fE5pe',
          input: {
            nodeId: 'BJsFnGN9pe',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'BJ6KhzV5Te',
            pinKey: 'out',
          },
        },
        'HJ-7Y3zE56e': {
          id: 'HJ-7Y3zE56e',
          input: {
            nodeId: 'BkyeKhzV56l',
            pinKey: 'a',
          },
          output: {
            nodeId: 'rkYt3G49px',
            pinKey: '__out__',
          },
        },
        HJEXF3zVc6l: {
          id: 'HJEXF3zVc6l',
          input: {
            nodeId: 'HJRtnME96g',
            pinKey: 'inp',
          },
          output: {
            nodeId: 'BkyeKhzV56l',
            pinKey: 'out',
          },
        },
        Hk5XYhzE56g: {
          id: 'Hk5XYhzE56g',
          input: {
            nodeId: 'HJ2Y2GV56l',
            pinKey: '__in__',
          },
          output: {
            nodeId: 'HJRtnME96g',
            pinKey: 'out',
          },
        },
        Sy87Ynz49Te: {
          id: 'Sy87Ynz49Te',
          input: {
            nodeId: 'BJ6KhzV5Te',
            pinKey: 'falseValue',
          },
          output: {
            nodeId: 'B15Y3z45ae',
            pinKey: '__out__',
          },
        },
        rkG7FhzVqTx: {
          id: 'rkG7FhzVqTx',
          input: {
            nodeId: 'BkyeKhzV56l',
            pinKey: 'b',
          },
          output: {
            nodeId: 'B15Y3z45ae',
            pinKey: '__out__',
          },
        },
        rkY7K3M4cal: {
          id: 'rkY7K3M4cal',
          input: {
            nodeId: 'HJRtnME96g',
            pinKey: 'falseValue',
          },
          output: {
            nodeId: 'rkYt3G49px',
            pinKey: '__out__',
          },
        },
        ryHXt2fEqax: {
          id: 'ryHXt2fEqax',
          input: {
            nodeId: 'BJ6KhzV5Te',
            pinKey: 'trueValue',
          },
          output: {
            nodeId: 'rkYt3G49px',
            pinKey: '__out__',
          },
        },
        ry_Xt2MV5Tl: {
          id: 'ry_Xt2MV5Tl',
          input: {
            nodeId: 'HJRtnME96g',
            pinKey: 'trueValue',
          },
          output: {
            nodeId: 'B15Y3z45ae',
            pinKey: '__out__',
          },
        },
      },
      nodes: {
        B15Y3z45ae: {
          id: 'B15Y3z45ae',
          pins: {},
          position: {
            x: 671,
            y: 110,
          },
          type: 'xod/core/input-number',
        },
        BJ6KhzV5Te: {
          id: 'BJ6KhzV5Te',
          pins: {},
          position: {
            x: 332,
            y: 386,
          },
          type: 'xod/core/either',
        },
        BJsFnGN9pe: {
          id: 'BJsFnGN9pe',
          pins: {},
          position: {
            x: 327,
            y: 497,
          },
          type: 'xod/core/output-number',
        },
        BkyeKhzV56l: {
          id: 'BkyeKhzV56l',
          pins: {},
          position: {
            x: 422,
            y: 204,
          },
          type: 'xod/core/less',
        },
        HJ2Y2GV56l: {
          id: 'HJ2Y2GV56l',
          pins: {},
          position: {
            x: 528,
            y: 497,
          },
          type: 'xod/core/output-number',
        },
        HJRtnME96g: {
          id: 'HJRtnME96g',
          pins: {},
          position: {
            x: 535,
            y: 383,
          },
          type: 'xod/core/either',
        },
        rkYt3G49px: {
          id: 'rkYt3G49px',
          pins: {},
          position: {
            x: 134,
            y: 91,
          },
          type: 'xod/core/input-number',
        },
      },
      path: 'xod/core/sort-pair',
      pins: {
        B15Y3z45ae: {
          description: '',
          direction: 'input',
          key: 'B15Y3z45ae',
          label: 'B15Y3z45ae',
          order: 1,
          type: 'number',
          value: 0,
        },
        BJsFnGN9pe: {
          description: '',
          direction: 'output',
          key: 'BJsFnGN9pe',
          label: 'BJsFnGN9pe',
          order: 0,
          type: 'number',
          value: 0,
        },
        HJ2Y2GV56l: {
          description: '',
          direction: 'output',
          key: 'HJ2Y2GV56l',
          label: 'HJ2Y2GV56l',
          order: 1,
          type: 'number',
          value: 0,
        },
        rkYt3G49px: {
          description: '',
          direction: 'input',
          key: 'rkYt3G49px',
          label: 'rkYt3G49px',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/split-bool': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.inp) {\n    return { outTrue: PULSE };\n  } else {\n    return { outFalse: PULSE };\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/split-bool',
      pins: {
        inp: {
          description: '',
          direction: 'input',
          key: 'inp',
          label: 'inp',
          order: 0,
          type: 'boolean',
          value: false,
        },
        outFalse: {
          description: '',
          direction: 'output',
          key: 'outFalse',
          label: 'outFalse',
          order: 1,
          type: 'pulse',
          value: false,
        },
        outTrue: {
          description: '',
          direction: 'output',
          key: 'outTrue',
          label: 'outTrue',
          order: 0,
          type: 'pulse',
          value: false,
        },
      },
    },
    'xod/core/stdout': {
      impls: {
        nodejs: 'module.exports.evaluate = function(e) {\n  var val = String(e.inputs.value);\n  process.stdout.write(val);\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/stdout',
      pins: {
        value: {
          description: '',
          direction: 'input',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'string',
          value: '',
        },
      },
    },
    'xod/core/time': {
      impls: {
        js: 'module.exports.evaluate = function(e) {\n  return { value: new Date().getTime() };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/time',
      pins: {
        pulse: {
          description: '',
          direction: 'input',
          key: 'pulse',
          label: 'pulse',
          order: 0,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/triggerable-number': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: e.props.value };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/triggerable-number',
      pins: {
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
        trigOn: {
          description: '',
          direction: 'input',
          key: 'trigOn',
          label: 'trigOn',
          order: 0,
          type: 'pulse',
          value: false,
        },
        value: {
          description: '',
          direction: 'input',
          key: 'value',
          label: 'value',
          order: 1,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/ultrasonic-hc-sr04': {
      impls: {
        espruino: "\nvar sonic = require('@amperka/ultrasonic');\n\nmodule.exports.setup = function(e) {\n  var pinTrig = new Pin(e.props.pinTrig);\n  var pinEcho = new Pin(e.props.pinEcho);\n  e.context.device = sonic.connect({\n    trigPin: pinTrig,\n    echoPin: pinEcho\n  });\n  e.context.units = e.props.units;\n  e.context.isBusy = false;\n};\n\nmodule.exports.evaluate = function(e) {\n  if (e.context.isBusy) {\n    e.fire({ error: \"busy\" });\n  } else {\n    e.context.isBusy = true;\n    e.context.device.ping(function(err, value) {\n      e.context.isBusy = false;\n      if (err) {\n        e.fire({ error: err.msg });\n      } else {\n        e.fire({ value: value });\n      }\n    }, e.context.units);\n  }\n};\n",
      },
      links: {},
      nodes: {},
      path: 'xod/core/ultrasonic-hc-sr04',
      pins: {
        error: {
          description: '',
          direction: 'output',
          key: 'error',
          label: 'error',
          order: 1,
          type: 'string',
          value: '',
        },
        sample: {
          description: '',
          direction: 'input',
          key: 'sample',
          label: 'sample',
          order: 0,
          type: 'pulse',
          value: false,
        },
        units: {
          description: '',
          direction: 'input',
          key: 'units',
          label: 'units',
          order: 1,
          type: 'string',
          value: '',
        },
        value: {
          description: '',
          direction: 'output',
          key: 'value',
          label: 'value',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/core/valveNumber': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  if (e.inputs.cond) {\n    e.fire({ out: e.inputs.in });\n  }\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/core/valveNumber',
      pins: {
        cond: {
          description: '',
          direction: 'input',
          key: 'cond',
          label: 'cond',
          order: 0,
          type: 'boolean',
          value: false,
        },
        in: {
          description: '',
          direction: 'input',
          key: 'in',
          label: 'in',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/math/add': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: (e.inputs.a + e.inputs.b) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/math/add',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/math/divide': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: (e.inputs.a / e.inputs.b) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/math/divide',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/math/multiply': {
      impls: {
        cpp: 'struct State {\n};\n\n{{ GENERATED_CODE }}\n\nvoid evaluate(NodeId nid, State* state) {\n    const Number in1 = getNumber(nid, Inputs::A);\n    const Number in2 = getNumber(nid, Inputs::B);\n    emitNumber(nid, Outputs::OUT, in1 * in2);\n}\n',
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: (e.inputs.a * e.inputs.b) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/math/multiply',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
    'xod/math/subtrac': {
      impls: {
        js: '\nmodule.exports.evaluate = function(e) {\n  return { out: (e.inputs.a - e.inputs.b) };\n};\n',
      },
      links: {},
      nodes: {},
      path: 'xod/math/subtrac',
      pins: {
        a: {
          description: '',
          direction: 'input',
          key: 'a',
          label: 'a',
          order: 0,
          type: 'number',
          value: 0,
        },
        b: {
          description: '',
          direction: 'input',
          key: 'b',
          label: 'b',
          order: 1,
          type: 'number',
          value: 0,
        },
        out: {
          description: '',
          direction: 'output',
          key: 'out',
          label: 'out',
          order: 0,
          type: 'number',
          value: 0,
        },
      },
    },
  },
};
