export const TABTEST_COMPILATION_RESULTS_FETCH_ERROR =
  'TABTEST_COMPILATION_RESULTS_FETCH_ERROR';
export const TABTEST_COMPILATION_ERROR = 'TABTEST_COMPILATION_ERROR';
export const TABTEST_EXECUTION_ABORT = 'TABTEST_EXECUTION_ABORT';
export const TABTEST_NONZERO_EXIT_CODE = 'TABTEST_NONZERO_EXIT_CODE';
export const WASM_NO_RUNTIME_FOUND = 'WASM_NO_RUNTIME_FOUND';
