export const CANT_FIND_LIB_BY_NAME = 'CANT_FIND_LIB_BY_NAME';
export const CANT_GET_LIB_XODBALL = 'CANT_GET_LIB_XODBALL';
export const CANT_FIND_LIB_VERSION = 'CANT_FIND_LIB_VERSION';
export const CANT_PARSE_LIBRARY_REQUEST = 'CANT_PARSE_LIBRARY_REQUEST';
export const INVALID_XODBALL = 'INVALID_XODBALL';
