export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export const LOAD_PROJECT_LIST = 'LOAD_PROJECT_LIST';
export const LOAD_PROJECT = 'LOAD_PROJECT';

export default {
  GET_PROJECT_LIST,
  LOAD_PROJECT_LIST,
  LOAD_PROJECT,
};
